name: Build and publish ISO image (debug mode)

on: workflow_dispatch

env:
  GRML_VERSION: "0.42.1"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Cache APT
        id: cache-apt
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives/
          key: ${{ runner.os }}-apt

      - name: Cache grml-live chroot
        id: cache-grml-chroot
        uses: actions/cache@v3
        with:
          path: grml/grml_chroot
          key: grml-chroot

      - name: Cache grml-live compressed chroot
        id: cache-grml-cd
        uses: actions/cache@v3
        with:
          path: grml/grml_cd
          key: grml-cd

      - name: Install grml-live
        run: |
          wget http://deb.grml.org/pool/main/g/grml-live/grml-live_${GRML_VERSION}_all.deb
          sudo apt-get update
          sudo apt-get install ./grml-live_${GRML_VERSION}_all.deb debian-archive-keyring -y --no-install-recommends

      - name: Build ISO
        id: grml-build
        if: ${{ success() }}
        run: |
          if [ -d grml_chroot ] || [ -d grml_chroot ]; then GRML_UPDATE='-u'; else GRML_UPDATE=''; fi
          sudo grml-live -C grml-live.conf -d 'date -u +"%Y-%m-%dT%H:%M:%SZ"' -F -i grml.iso ${GRML_UPDATE} -V

      - name: Upload grml-live log as an artifact
        id: upload-log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: grml-live.log
          path: grml/grml_logs/grml-live.log

      - name: Upload grml ISO as a release
        id: upload-iso
        if: ${{ steps.grml-build.conclusion == 'success' }}
        uses: softprops/action-gh-release@v1
        with:
          files: ./grml/grml_isos/grml.iso
          tag_name: unstable
          draft: true
          name: ${{ github.sha }}

      - name: List files
        if: always()
        run: ls -lah ./ ./grml/ ./grml/*
