name: Build and publish ISO image daily
run-name: build-daily

on:
  schedule:
    - cron: '13 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Build ISO
        id: grml-build
        if: ${{ success() }}
        run: sudo ./auto-build.sh -V

      - name: Export environnement
        id: grml-env
        if: always()
        run: cat .env >> $GITHUB_ENV

      - name: Upload grml-live log as an artifact
        id: upload-log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: grml-logs
          path: ${{ env.OUTPUT }}/grml_logs/

      - name: Upload grml ISO as a release
        id: upload-iso
        if: ${{ steps.grml-build.conclusion == 'success' }}
        uses: pyTooling/Actions/releaser/composite@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            - ${{ env.OUTPUT }}/grml_isos/*.iso
            - ${{ env.OUTPUT }}/grml_isos/*.iso.sha256
          tag: nightly
          rm: true
