name: Build image but don't publish it

on: 
  workflow_dispatch:
  push:
    paths-ignore: 
      - '.github**'
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build ISO
        id: grml-build
        if: ${{ success() }}
        run: sudo ./auto-build.sh --fast -V

      - name: Export environnement
        id: grml-env
        if: always()
        run: cat .env >> $GITHUB_ENV

      - name: Upload grml-live log as an artifact
        id: upload-log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: grml-logs
          path: ${{ env.OUTPUT }}/grml_logs/

      - name: Upload grml-live iso as an artifact
        id: upload-iso
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: grml-iso
          path: |
            - ${{ env.OUTPUT }}/grml_isos/*.iso
            - ${{ env.OUTPUT }}/grml_isos/*.iso.sha256

      - name: List files
        if: always()
        run: ls -lah ./ ./build/ ./build/*
