name: Build image but don't publish it

on: 
  workflow_dispatch:
  push:
    paths-ignore: 
      - '.github**'
    branches: [main, master]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Cache APT
        id: cache-apt
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives/
          key: ${{ runner.os }}-apt

      - name: Build ISO
        id: grml-build
        if: ${{ success() }}
        run: sudo ./auto-build.sh -V

      - name: Upload grml-live log as an artifact
        id: upload-log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: grml-live
          path: |
            - grml/grml_logs/grml-live.log
            - grml/grml_isos/grml.iso

      - name: List files
        if: always()
        run: ls -lah ./ ./grml/ ./grml/*
