name: Build and publish ISO image (debug mode)

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Build ISO
        id: grml-build
        if: ${{ success() }}
        run: sudo ./auto-build.sh --fast -V

      - name: Export environnement
        id: grml-env
        if: always()
        run: cat .env >> $GITHUB_ENV

      - name: Upload grml-live log as an artifact
        id: upload-log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: grml-logs
          path: ${{ env.OUTPUT }}/grml_logs/

      - name: Upload grml ISO as a release
        id: upload-iso
        if: ${{ steps.grml-build.conclusion == 'success' }}
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          files:
            - ${{ env.OUTPUT }}/grml_isos/grml-full-bullseye-${{ env.ISO_DATE }}.iso
            - ${{ env.OUTPUT }}/grml_isos/grml-full-bullseye-${{ env.ISO_DATE }}.iso.sha256
          generateReleaseNotes: true
          draft: true
          tag: unstable
          name: ${{ github.sha }}

      - name: List files
        if: always()
        run: ls -lah ./ ./grml/ ./grml/*
