name: Build and publish ISO image daily
run-name: build-daily

on:
  schedule:
    - cron: '16 1 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Cache APT
        id: cache-apt
        uses: actions/cache@v3
        with:
          path: /var/cache/apt/archives/
          key: ${{ runner.os }}-apt

      - name: Cache grml-live chroot
        id: cache-grml-chroot
        uses: actions/cache@v3
        with:
          path: grml/grml_chroot
          key: grml-chroot

      - name: Cache grml-live compressed chroot
        id: cache-grml-cd
        uses: actions/cache@v3
        with:
          path: grml/grml_cd
          key: grml-cd

      - name: Build ISO
        id: grml-build
        if: ${{ success() }}
        run: sudo ./auto-build.sh

      - name: Upload grml-live log as an artifact
        id: upload-log
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: grml-live.log
          path: grml/grml_logs/grml-live.log

      - name: Upload grml ISO as a release
        id: upload-iso
        if: ${{ steps.grml-build.conclusion == 'success' }}
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: ./grml/grml_isos/grml.iso
          name: "Daily build"
          tag_name: daily
